#ifndef _H_TqkLibraryAudioPlayerXAudio2Native_H_
#define _H_TqkLibraryAudioPlayerXAudio2Native_H_

TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS XAudio2Engine* XAudio2Engine_Alloc();
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS void XAudio2Engine_Free(XAudio2Engine** ppEngine);

TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS XAudio2MasterVoice* XAudio2MasterVoice_Alloc(const XAudio2Engine* pEngine, int nb_channels, int sample_rate);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS XAudio2MasterVoice* XAudio2MasterVoice_Alloc_AVFrame(const XAudio2Engine* pEngine, const AVFrame* pFrame);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS void XAudio2MasterVoice_Free(XAudio2MasterVoice** ppMasterVoice);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS BOOL XAudio2MasterVoice_SetVolume(XAudio2MasterVoice* pMasterVoice, FLOAT volume);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS VOID XAudio2MasterVoice_GetVolume(XAudio2MasterVoice* pMasterVoice, FLOAT* pVolume);

TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS XAudio2SourceVoice* XAudio2SourceVoice_Alloc(const XAudio2MasterVoice* pMasterVoice, const AVFrame* pFrame);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS void XAudio2SourceVoice_Free(XAudio2SourceVoice** ppSourceVoice);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS BOOL XAudio2SourceVoice_Start(XAudio2SourceVoice* pSourceVoice);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS BOOL XAudio2SourceVoice_Stop(XAudio2SourceVoice* pSourceVoice, UINT32 flag = 0);//0 or XAUDIO2_PLAY_TAILS
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS BOOL XAudio2SourceVoice_SetVolume(XAudio2SourceVoice* pSourceVoice, FLOAT volume);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS VOID XAudio2SourceVoice_GetVolume(XAudio2SourceVoice* pSourceVoice, FLOAT* volume);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS BOOL XAudio2SourceVoice_SetChannelVolumes(XAudio2SourceVoice* pSourceVoice, UINT32 channels, const FLOAT* pVolume);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS VOID XAudio2SourceVoice_GetChannelVolumes(XAudio2SourceVoice* pSourceVoice, UINT32 channels, FLOAT* pVolume);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS VOID XAudio2SourceVoice_GetVoiceDetails(XAudio2SourceVoice* pSourceVoice, XAUDIO2_VOICE_DETAILS* pVoiceDetails);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS XAudio2SourceQueueResult XAudio2SourceVoice_QueueFrame(XAudio2SourceVoice* pSourceVoice, const AVFrame* pFrame, BOOL isEof);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS BOOL XAudio2SourceVoice_FlushSourceBuffers(XAudio2SourceVoice* pSourceVoice);

#if _DEBUG
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS DebugAudioSource* DebugAudioSource_Alloc(LPSTR filePath);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS VOID DebugAudioSource_Free(DebugAudioSource** ppAudioSource);
TQKLIBRARYAUDIOPLAYERXAUDIO2NATIVEEXPORTS BOOL DebugAudioSource_ReadFrame(DebugAudioSource* pAudioSource, AVFrame* pframe);
#endif

#endif // !ScrcpyNativeExports_H
